name = "tekton-by-bigie"
compatibility_date = "2026-09-24"
account_id = "bfcff7ae9588a5fc7545d2a9be3272ef"
main = "src/worker.js"

routes = [
  { pattern = "tektonbybigie.com", custom_domain = true },
  { pattern = "www.tektonbybigie.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "DRAFT_CREDENTIALS"
id = "89b17f1d3a894d84a5612ad0b011a815"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true
